export const STATE_FETCHED_DATA_SUCCESS = 'STATE_FETCHED_DATA_SUCCESS';
export const STATE_LIST_REQUEST = 'STATE_LIST_REQUEST';
export const STATE_GET_FAILURE = 'STATE_GET_FAILURE';
export const STATE_GET_DROPDOWN_LIST = "STATE_GET_DROPDOWN_LIST";
export const STATE_FILTER_LIST_REQUEST='STATE_FILTER_LIST_REQUEST'