
export const BEN_INT_FETCHED_DATA_SUCCESS = "BEN_INT_FETCHED_DATA_SUCCESS";
export const BEN_INT_LIST_REQUEST = "BEN_INT_LIST_REQUEST";
export const BEN_INT_GET_FAILURE = "BEN_INT_GET_FAILURE";
export const BEN_INT_GET_DROPDOWN_LIST = "BEN_INT_GET_DROPDOWN_LIST";
