export const GRAMPANCHAYAT_FETCHED_DATA_SUCCESS = 'GRAMPANCHAYAT_FETCHED_DATA_SUCCESS';
export const GRAMPANCHAYAT_LIST_REQUEST = 'GRAMPANCHAYAT_LIST_REQUEST';
export const GRAMPANCHAYAT_GET_FAILURE = 'GRAMPANCHAYAT_GET_FAILURE';
export const GRAMPANCHAYAT_GET_DROPDOWN_LIST = 'GRAMPANCHAYAT_GET_DROPDOWN_LIST';


