
export const COMM_INT_FETCHED_DATA_SUCCESS = "COMM_INT_FETCHED_DATA_SUCCESS";
export const COMM_INT_LIST_REQUEST = "COMM_INT_LIST_REQUEST";
export const COMM_INT_GET_FAILURE = "COMM_INT_GET_FAILURE";
export const COMM_INT_GET_DROPDOWN_LIST = "COMM_INT_GET_DROPDOWN_LIST";
