export const VILLAGE_FETCHED_DATA_SUCCESS = 'VILLAGE_FETCHED_DATA_SUCCESS';
export const VILLAGE_LIST_REQUEST = 'VILLAGE_LIST_REQUEST';
export const VILLAGE_GET_FAILURE = 'VILLAGE_GET_FAILURE';
export const VILLAGE_GET_DROPDOWN_LIST = 'VILLAGE_GET_DROPDOWN_LIST';