export const BENEFICIARY_CREATE_SUCCESS = "BENEFICIARY_CREATE_SUCCESS";
export const BENEFICIARY_CREATE_REQUEST = "BENEFICIARY_CREATE_REQUEST";
export const BENEFICIARY_CREATE_FAILURE = "BENEFICIARY_CREATE_FAILURE";
export const BENEFICIARY_FETCHED_DATA_SUCCESS =
  "BENEFICIARY_FETCHED_DATA_SUCCESS";
export const BENEFICIARY_LIST_REQUEST = "BENEFICIARY_LIST_REQUEST";
export const BENEFICIARY_GET_FAILURE = "BENEFICIARY_GET_FAILURE";
export const BENEFICIARY_GET_DROPDOWN_LIST = "BENEFICIARY_GET_DROPDOWN_LIST";
export const BENEFICIARY_DELETE_REQUEST = "BENEFICIARY_DELETE_REQUEST";
export const BENEFICIARY_DELETE_SUCCESS = "BENEFICIARY_DELETE_SUCCESS";
export const BENEFICIARY_DELETE_FAILURE = "BENEFICIARY_DELETE_FAILURE";

export const BENEFICIARY_SELECTED_IDS = "BENEFICIARY_SELECTED_IDS";
